### ISSUE TITLE
Not compatile with DBT 0.17

### ISSUE THREAD

**Issue by bashyroger** [fishtown-analytics/dbt-codegen#21]
I am getting an error when trying to install this package in DBT 0.17, seems it needs to be updated

RPCException(10006, Dependency Error, {'type': 'DependencyException', 'message': "Version error for package fishtown-analytics/dbt_utils: Could not find a satisfactory version from options: ['=0.3.0', '>=0.1.25', '>=0.1.25', '<0.3.0']"

**Comment by clrcrl** [comment]
Addressed by #23
