### ISSUE TITLE
Feature: Add param for making leading commas

### ISSUE THREAD

**Issue by carlyfk** [fishtown-analytics/dbt-codegen#30]
### Describe the feature
Some people prefer to have leading commas in their select statements. This optional parameter would generate the source SQL with leading commas.

### Are you interested in contributing this feature?
I'll work on this sometime since I'm probably the only person who will want this (along with @Nerdenberger ) 😂

**Comment by clrcrl** [comment]
Heh, you would make a lot of people happy with this!
